---
  
- hosts: app
  gather_facts: yes
  become: yes

  tasks:

  - name: Install Docker Ubuntu
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - docker
      - docker.io
    when: ansible_os_family == "Debian"



  - name: Install docker
    yum:
      name: docker
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Docker systemd
    systemd:
      name: docker
      enabled: yes
      state: started


- hosts: database
  user: root
  become: true
  become_method: sudo
  become_user: root
  gather_facts: yes

  tasks:

  - name: "Install PostgreSQL version {{ pg_ver }}"
    apt:
      name: "postgresql-{{ pg_ver }}"
      state: present
      

  - name: "Create {{ pg_data }} Directory"
    file:
      path: "{{ pg_data }}"
      state: directory
      owner: postgres
      group: postgres
      mode: 0750

  - name: Register Contents of PGDATA Folder
    shell: "ls {{ pg_data }}"
    register: pg_contents

  - name: Initialize PostgreSQL
    shell: "/usr/lib/postgresql/{{ pg_ver }}/bin/initdb"
    environment:
      PGDATA: "{{ pg_data }}"
    when: pg_contents["stdout_lines"] | length == 0
    become: yes
    become_user: postgres

  - name: Setting postgres
    replace:
      path: "/etc/postgresql/{{ pg_ver }}/main/postgresql.conf"
      regexp: "^data_directory =.*$"
      replace: "data_directory = '{{ pg_data }}'"
    notify:
      - reload postgres

  - name: Postgresql systemd enable
    systemd:
      name: "postgresql@{{ pg_ver }}-main"
      enabled: yes
      state: started

  handlers:

  - name: reload postgres
    systemd:
      name: "postgresql@{{ pg_ver }}-main"
      state: restarted

